name: Upload Python Package
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__

          TWINE_PASSWORD: ${{ secrets.TOKEN }}

        run: |
          uv build
          uv run --with twine twine upload dist/*
